### ISSUE TITLE
Question: Color per face/vertex

### ISSUE THREAD

**Issue by iimanu** [pyvista/pyvista-support#114]
Hi there,

I'm not sure whether this feature exists or not, but I'm looking to plots meshes and point-clouds with a per-vertex or per-face vector of colors. Specifically, I'd like to supply to `add_mesh`: [number_faces x 3]/[number_vertices x 3]  tensor of RGB values, allowing me to plot a point-wise function over the faces/vertices. This can be used for many applications, such as visualizing semantic mesh segmentation/differential operators/curvature and many more. 

Currently, add_mesh does not receive a tensor of colors, as described. So, my requests are: 
1. Is there a quick workaround you can offer?
2. I'd like to request this as a feature request.

-- Mano

**Comment by banesullivan** [comment]
Hi there, @iimanu, I moved this to the `pyvista-support` repo as this is a usage question rather than an issue/feature request.

Just to be complete in case others stumble upon this question, [here](https://docs.pyvista.org/examples/00-load/read-image.html) is an example of plotting RGB values on a mesh from the example gallery. You do this by using the `rgb` argument to `add_mesh`

@iimanu, it would be really great if you could share your solution with example data for others to reference when they have the same problem.
