### ISSUE TITLE
Remove point_labels

### ISSUE THREAD

**Issue by motiurce** [pyvista/pyvista-support#118]
## Description
How can I remove point labels? 
If possible please help me. 

## Example Data
I am trying like this-
lp=plotter.add_point_labels(points[mask], values[mask].tolist(), font_size=24)
plotter.remove_actor(lp) 
but not working.

**Comment by GuillaumeFavelier** [comment]
Hello @motiurce, thank you for your interest in PyVista! 

Actually, the function `add_point_labels()` returns a `vtkMapper` instead of a `vtkActor`. This behavior is a bit different from others functions available in the API I admit, we could definitely improve consistency there. 

To provide an immediate answer, I could recommend you to set the parameter `name` of `add_point_labels()` and then call `remove_actor()` with this same name.

**Comment by banesullivan** [comment]
This is a good issue! Perhaps we should do a refactor of all the methods in the `BasePlotter` /`Renderer` class that “add” things to the scene to make sure they return the actor that was added

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akaszynski** [comment]
Agreed, we should have consistent returns.  Returning the actor is the most common and useful; I say we go with that.

**Comment by GuillaumeFavelier** [comment]
+1 for returning actors
