### ISSUE TITLE
Interpolation from Unstructured mesh to Structured Mesh and back

### ISSUE THREAD

**Issue by c-quilo** [pyvista/pyvista-support#148]
Hi, I've been trying to interpolate from an unstructured mesh to a structured mesh and back with pyvista. However, any time I try to interpolate back, there's an error with the number of arrays between "result" and "mesh". I've been trying eliminating arrays from "result", but I cannot get around it. Any help would be highly appreciated.

Thanks and be safe
[LSBU_100.vtu.zip](https://github.com/pyvista/pyvista-support/files/4422834/LSBU_100.vtu.zip)

```py
import pyvista as pv
import numpy as np

filename = 'LSBU_100.vtu'

mesh = pv.read(filename)

size = 64
x = np.linspace(-359.7, 359.7, size)
y = np.linspace(-338.1, 338.1, size)
z = np.linspace(0.2, 250, size)
x, y, z = np.meshgrid(x, y, z)
print(x.shape)

# Create the unstructured grid directly from the numpy arrays and plot
grid = pv.StructuredGrid(x, y, z, radius = 5)
result = grid.interpolate(mesh)

# Interpolate back to unstructured mesh
result2 = mesh.interpolate(result)
```
This is the error I get:

ERROR:root:Cannot interpolate arrays of different type.

**Comment by banesullivan** [comment]
Question: why interpolate twice?

Maybe glance over the docs for both the [`interpolate`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.interpolate) and the [`sample`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.sample) filters just to make sure these filters are doing what you want them to do.

----

Anyways, the problem seems to be coming from some of the automatically generated arrays in the first interpolation (`vtkValidPointMask` and the two`vtkGhostType` arrays). These arrays are messing up the interpolation on the VTK backend. To make your workflow run, copy that mesh and delete those arrays.

Also, I'm skeptical of doing the second interpolation so here is a workflow that just does a sampling of the interpolated mesh back on to the original mesh. A few notes:

- I made sure the created `StructuredGrid`'s bounds fully encompassed the original mesh
- I use sampling on the second round as I don't think you actually want to interpolate there

```py
import pyvista as pv 
import numpy as np

filename = 'LSBU_100.vtu'
mesh = pv.read(filename)

size = 64
x = np.linspace(-359.7, 359.7, size)
y = np.linspace(-338.1, 338.1, size)
z = np.linspace(0.2, 250, size)
x, y, z = np.meshgrid(x, y, z)

# Create the unstructured grid directly from the numpy arrays and plot
grid = pv.StructuredGrid(x, y, z)
result = grid.interpolate(mesh, radius=20.)

# Resample back to unstructured mesh
foo = mesh.copy()
foo.clear_arrays()
result2 = foo.sample(result)

p = pv.Plotter(notebook=False, shape=(1,3))
p.add_mesh(mesh, show_edges=0)
p.subplot(0,1)
p.add_mesh(result, show_edges=0)
p.subplot(0,2)
p.add_mesh(result2, show_edges=0)
p.link_views()
p.show()
```

<img width="1416" alt="Screen Shot 2020-04-02 at 9 46 51 PM" src="https://user-images.githubusercontent.com/22067021/78315588-78443180-752b-11ea-8f9a-fb2ea35daacc.png">

**Comment by c-quilo** [comment]
Thanks!. This is exactly what I needed
