### ISSUE TITLE
Density on the surface of a sphere using PyVista

### ISSUE THREAD

**Issue by bisejdiu** [pyvista/pyvista-support#153]
Hi everyone, 

I would like to map the 3D density of an x, y, z array on the surface of a PyVista sphere. To be more exact, have a look at the following [example](https://github.com/janpipek/physt#3d-directional-example) from the `physt` package. 

My goal is to achieve the same result using  PyVista. 

Here's an example to reproduce the results from the above link (if you don't want to install the library). 
[data.zip](https://github.com/pyvista/pyvista-support/files/4446445/data.zip)

```python
import pickle

with open('data.pkl', 'rb') as pickle_data:
    physt_data = pickle.load(pickle_data)
```

and then (using code that I copied from the `physt ` source code): 

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

# histogram and edges
H, e = physt_data 

cmap = plt.get_cmap('rainbow')

norm = colors.Normalize(H.min(), H.max(), clip=True)
cmap_data = norm(H)
cols = cmap(cmap_data)

r = 1
xs = r * np.outer(np.sin(e[0]), np.cos(e[1]))
ys = r * np.outer(np.sin(e[0]), np.sin(e[1]))
zs = r * np.outer(np.cos(e[0]), np.ones(H.shape[1] + 1))

show_zero = True

fig = plt.figure()
ax = Axes3D(fig)

for i in range(H.shape[0]):
    for j in range(H.shape[1]):
        if not show_zero and not data[i, j]:
            continue
        x = xs[i, j], xs[i, j + 1], xs[i + 1, j + 1], xs[i + 1, j]
        y = ys[i, j], ys[i, j + 1], ys[i + 1, j + 1], ys[i + 1, j]
        z = zs[i, j], zs[i, j + 1], zs[i + 1, j + 1], zs[i + 1, j]
        
        verts = [list(zip(x, y, z))]
        col = Poly3DCollection(verts)
        col.set_facecolor(cols[i, j])
        col.set_edgecolor("black")
        ax.add_collection3d(col)

ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_zlabel("z")

ax.set_xlim(-1.1, 1.1)
ax.set_ylim(-1.1, 1.1)
ax.set_zlim(-1.1, 1.1)
```
![result](https://user-images.githubusercontent.com/15002808/78706612-9a8fd380-78cc-11ea-9a4e-c9b0c1b11f7b.png)

Of course, I don't necessarily have to do everything with PyVista. Using the histogram and edges calculated from `physt` would be perfectly fine. 

Thank you

**Comment by banesullivan** [comment]
There are, of course, many ways to do this with PyVista. Considering you really have a 2D meshgrid that you project to a sphere, you could simply define the spherical mesh as a `pyvista.StructuredGrid` since the coordinates have an internal grid/lattice.

Your code:
```py
import pickle
import pyvista as pv
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors

with open('data.pkl', 'rb') as pickle_data:
    physt_data = pickle.load(pickle_data)

H, e = physt_data 

r = 1
xs = r * np.outer(np.sin(e[0]), np.cos(e[1]))
ys = r * np.outer(np.sin(e[0]), np.sin(e[1]))
zs = r * np.outer(np.cos(e[0]), np.ones(H.shape[1] + 1))

# Concate into an XYZ array
nodes = np.c_[xs.ravel(), ys.ravel(), zs.ravel()]
```

PyVista code:

```py
# Make a StructuredGrid
grid = pv.StructuredGrid()
# Set the vertices
grid.points = nodes
# Set the vertices' lattice dimensions
grid.dimensions = [17, 17, 1]
# Add the scalar data values as cell data
grid["H"] = H.ravel()

# Plot just that mesh
grid.plot(cmap="rainbow")
```

![download](https://user-images.githubusercontent.com/22067021/78731963-4528e600-790f-11ea-97df-0f66a1d0d749.png)

**Comment by bisejdiu** [comment]
This is really cool! I only have one question left although this issue is technically closed. `grid ` has an interpolation method which I assume means I can interpolate the histogram?. How would I call it in this instance?

**Comment by banesullivan** [comment]
> `grid` has an interpolation method which I assume means I can interpolate the histogram?

That interpolation method will perform a Gaussian based interpolation of the data on another mesh to that mesh. You already have that data on living on the cells of the `grid` mesh, so what exactly do you want to do?

Perhaps you want the data on the nodes of the mesh to make the coloring a bit more smooth - where the values are interpolated across the cells from the nodes? In that case, try:

```py
nodal = grid.cell_data_to_point_data()
nodal.plot(clim=[0,530], cmap="rainbow")
```

![download](https://user-images.githubusercontent.com/22067021/78788474-daf95b00-7979-11ea-90cf-9296cf5f0975.png)


Unfortunately, the gridded mesh here has an open edge (seen on the left there) because it's actually a 2D flat grid projected to a sphere. We can mitigate this by casting to `PolyData` and cleaning the mesh to merge he points along that edge from pole to pole, but this process will remove some data/information:

```py
clean = nodal.extract_surface().clean(tolerance=0.001,)
clean.plot(clim=[0,530], cmap="rainbow")
```

![download](https://user-images.githubusercontent.com/22067021/78789069-a2a64c80-797a-11ea-9cce-72007d5bb0a6.png)

**Comment by bisejdiu** [comment]
This is perfect. Thank you!
