### ISSUE TITLE
Create continuous polyline from mesh slice

### ISSUE THREAD

**Issue by j-polden** [pyvista/pyvista-support#169]
## Description

Hi All. I have been using the `slice_along_axis()` function to slice a mesh, which has been working well. I want to create some polylines from these slices, however the `PolyData.lines` produced from the slicing operation do not appear to be connected in series. I was about to write a function which steps through the coordinates and re-orders the lines to place them in series, however I figured I'd ask here before embarking. 

VTK has the vtkstripper filter which can perform this operation and was wondering if pyvista has some similar functionality?

**Comment by banesullivan** [comment]
Hm, can you provide some screenshots and the code you currently have (and even data if you can) to help us understand the task a bit better?

**Comment by j-polden** [comment]
Hi Bane, sure thing. 

```
import pyvista
from pyvista import examples
import numpy as np

mesh = examples.load_airplane()  
slice = mesh.slice(normal='z', origin=(0,0,-10))
assert not slice.lines.shape[0] % 3, 'cells must all be edges' 

edge_indexes = slice.lines.reshape(int(slice.lines.shape[0]/3),3)[:,1:]
edge_coordinates = np.array(slice.points[edge_indexes])
```

The edge coordinates array above contains each edge in the slice with a [start_point,end_point] type of structure for each edge.

If you take a look at the list of edge coordinates, they don't link up 'head-to-tail' if you walk through them. What I would like do do is filter/re-arrange them so they are in order and if you walk through them sequentially, they form a continuous polyline. I know that vtkStripper has this functionality, and I was considering writing some sort of function to do this, but I figured I'd check in here first to see if this work has been done already.

Cheers!

**Comment by banesullivan** [comment]
Ah, this is a really awesome demo and thanks for including the pictures!! 

A long time ago I ran into a similar issue and had a workaround by contouring instead of slicing. It would be good to develop a generalized routine using `vtkStripper` to do this and include it in PyVista as we do not currently leverage that class.

If you are able to put together a function using `vtkStripper` please be sure to share it here or better yet create a PR in `PyVista` to make a new `PolyData` filter. 

FYI, I may give this a shot myself in the next few days or I would be happy to take whatever you create and generalize it to include in  PyVista

**Comment by banesullivan** [comment]
In the meantime, you can use `vtkStripper` to create a single PolyLine cell of the line segments you have:

```py
import vtk
alg = vtk.vtkStripper()
alg.SetInputDataObject(slice)
alg.Update()
stripped = pv.wrap(alg.GetOutput())
```

**Comment by akaszynski** [comment]
@banesullivan, is this something we should implement in `filters.py`.

**Comment by j-polden** [comment]
@banesullivan  that small code snippet works amazingly well. Integration into pyvista would be fantastic
