### ISSUE TITLE
pyvista object creation from 3-D numpy arrays

### ISSUE THREAD

**Issue by elbeejay** [pyvista/pyvista-support#180]
## Description
I apologize if this is a bit trivial, but I think the following example may illustrate a common hurdle preventing wider use of `pyvista` (which seems to be a pretty neat tool by the way). 

The central question I have is: From a 3-D numpy ndarray, how do I create a `pyvista` object that filtering functions can be performed on (i.e. something analogous to the mesh loaded by `examples.load_channels()` for example)?

The below example script is based on the [Creating a Uniform Grid](https://docs.pyvista.org/examples/00-load/create-uniform-grid.html#sphx-glr-examples-00-load-create-uniform-grid-py) example. In the example below we create a 3-D numpy array of 0s and put some 1 values in the center of the cube. When this is translated into the `pyvista.UniformGrid()` object and visualized, the 1 values are not visible in the plot despite existing in the object (as evidenced by the colorbar reaching up to 1.0). 

Is this the best way to create a `pyvista` object from a uniformly spaced 3-D numpy array? I don't believe the `pyvista.UniformGrid()` object can be sliced in the same way a mesh can, so what is the best practice for converting from the `pyvista.UniformGrid()` to a mesh, or should the mesh be the object that is generated from a 3-D array as opposed to the `pyvista.UniformGrid()`?

Thanks!

## Example Script
```py
import numpy as np
import pyvista as pv

box = np.zeros((5, 5, 5))
box[1:4, 1:4, 1:4] = 1.

# make pyvista grid
grid = pv.UniformGrid()
grid.dimensions = box.shape
grid.spacing = (1, 1, 1)
grid.point_arrays['values'] = box.flatten()

# plot grid
grid.plot(opacity=0.5, show_edges=True)
```

![image](https://user-images.githubusercontent.com/1770513/84570332-86e06d80-ad52-11ea-9b9d-371085a0efec.png)

**Comment by banesullivan** [comment]
> Is this the best way to create a pyvista object from a uniformly spaced 3-D numpy array?


That is the explicit/general way to create a PyVista UniformGrid from a 3D numpy array. Since 3D numpy arrays are ubiqutious, we directly support them in the `wrap` method (which is typically meant for taking VTK data objects). The easiest way is to create a PyVista mesh from a 3D numpy array is: `grid = pv.wrap(box)`. You can still edit the spacing/origin/etc after wrapping it too.

```py
import numpy as np
import pyvista as pv

box = np.zeros((5, 5, 5))
box[1:4, 1:4, 1:4] = 1.

# make pyvista grid
grid = pv.wrap(box)

# plot grid
grid.plot(opacity=0.5, show_edges=True)
```

>  I don't believe the pyvista.UniformGrid() object can be sliced in the same way a mesh can, so what is the best practice for converting from the pyvista.UniformGrid() to a mesh, or should the mesh be the object that is generated from a 3-D array as opposed to the pyvista.UniformGrid()?

A `UniformGrid` can be sliced in all the same ways as any other PyViata mesh! It is a "mesh" as far as we are concerned (see [this](https://docs.pyvista.org/getting-started/what-is-a-mesh.html) for more context on PyVista data structures and why we use the term "mesh" very loosely).

```py
slc = grid.slice()
slc.plot(show_edges=True)
```

![download](https://user-images.githubusercontent.com/22067021/84575464-1a2d9900-ad7b-11ea-9a1c-688c93b7d4d2.png)



```py
slcs = grid.slice_orthogonal()
slcs.plot(show_edges=True)
```
![download](https://user-images.githubusercontent.com/22067021/84575468-20237a00-ad7b-11ea-99b9-853459d53092.png)

**Comment by elbeejay** [comment]
Thanks! That is super helpful
