### ISSUE TITLE
sample_over_line produces spurious zero values in UnstructuredGrid

### ISSUE THREAD

**Issue by fbeaudo** [pyvista/pyvista-support#201]
## Description

I am working with an UnstructuredGrid and I want to plot the quantity over a line. The quantity (called 'eps') is defined at the nodes of the grid.
I saved the .vtk file for my grid (see below). Plotting the quantity gives me the result I expect. The same is true using slices. These two methods both give me a value that is non-zero everywhere.
However, if I produce a linecut of the same quantity 'eps' using the sample_over_line method, then some spurious zeros appear in the output data. This can also be seen using plot_over_line.
This appears to be a bug, since my quantity should not be zero along this linecut. This can easily be seen from the 3D plots.
I am using pyvista version 0.25.3 along with vtk version 9.0.1. I had the same issue with pyvista 0.24.2. I would appreciate to know what could be causing this.
Here is the code that shows the apparent bug.

```py
""" sample_over_line.py: Test pyvista function sample_over_line."""

__author__ = "Felix Beaudoin"
__copyright__ = "Copyright 2020, Nanoacademic Technologies Inc."

import pyvista as pv

# Load vtk file and initialize grid
path = "pyvistagrid.vtk"
grid = pv.UnstructuredGrid(path)

# Plot the quantity 'eps' stored in .vtk file
# It is clearly non-zero everywhere
# This is also true when inspecting the .vtk file
grid.plot()
slices = grid.slice_orthogonal()
slices.plot()

# Now plot over a line from x=-12e-9 to x=12e-9 at z=5e-9 and y=0.
begin = [-12e-9,0,5e-9]
end = [12e-9,0,5e-9]
grid.plot_over_line(begin,end,resolution=100)

# The plot shows dips at which 'eps' goes to 0 exactly
# This is also seen by directly printing the linecut
linecut = grid.sample_over_line(begin,end,resolution=100)
print(linecut.point_arrays['eps'])
```

## Example Data

The vtk file used in the code is also attached in the following zip file.
[pyvistagrid.zip](https://github.com/pyvista/pyvista-support/files/4905222/pyvistagrid.zip)

**Comment by banesullivan** [comment]
So the `sample_over_line` and `plot_over_line` filters do not have access to the `tolerance` argument which is what you need to adjust. Try using the `sample` filter directly to control the tolernace:


```py
# Now plot over a line from x=-12e-9 to x=12e-9 at z=5e-9 and y=0.
begin = [-12e-9,0,5e-9]
end = [12e-9,0,5e-9]
line = pv.Line(begin, end, resolution=100)
linecut = line.sample(grid, tolerance=0.5)

import matplotlib.pyplot as plt
plt.plot(linecut.point_arrays['eps'])
```

![download](https://user-images.githubusercontent.com/22067021/87205073-8943d200-c2d4-11ea-9101-f577ca5468b9.png)

-----

https://github.com/pyvista/pyvista/pull/828 adds access to that argument in these filters. In the meantime, manually create you're line and directly use the `sample` filter

**Comment by banesullivan** [comment]
The problem was that some of the nodes of the line were falling too far away from any nodes in the mesh, so we have to bump the tolerance to make sure we capture all of the data

**Comment by fbeaudo** [comment]
@banesullivan Thanks a lot. This was incredibly helpful ! However, I looked into the documentation of pyvista and vtk for a precise definition of the tolerance, but could not find it anywhere. The best I could find is : 
« tolerance used to compute whether a point in the source is in a cell of the input»
Would you happen to know what the exact criterion is ? Is it a minimum distance to be considered outside the line ?

**Comment by banesullivan** [comment]
the tolerance is an absolute distance used to compute whether the probing point is near enough to a point to sample its value.

In essence, set the tolerance to `0.5` and a sphere of radius `0.5` is generated around each probing point. The vertex with the minimum distance to the probing point within that sphere is the vertex to be sampled. Anything outside that sphere will be ignored. If no vertices of the sampled mesh fall within that sphere, then a zero value is given and that point is marked in the valid points mask array that is also yielded by that filter.

In the example you have, the line is much denser than the input mesh and nodes of that line might fall well in the center of the cells created by the points being sampled. This means many of the probing points are all sampling the same nodes in the input mesh. When the VTK filter autogenerates the tolerance, you get something far smaller than you should use because the sampling line is so dense.

**Comment by fbeaudo** [comment]
@banesullivan thanks again ! This is exactly what I needed to know. Have a great day !
