### ISSUE TITLE
Elevation Filter Saturation/Colouring

### ISSUE THREAD

**Issue by montymagic9** [pyvista/pyvista-support#216]
## Description

Is there any way of making the elevation filter more saturated? In the example below you can see the box displayed is quite unsaturated compared to the image below it. Is there any way of achieving more distinction between the colours? So for example i'd see the difference between red and yellow more clearly. (I changed the pv theme to rainbow in the source code to achieve the rainbow colouring).

I understand the box creates the perfect gradient but even on more scattered data it is still looking very unsaturated.

## Example Data

![pyvista_new1](https://user-images.githubusercontent.com/5530323/88857177-b1489600-d1ed-11ea-91e6-d0b2111b16a2.PNG)

![pyvista_colour2](https://user-images.githubusercontent.com/5530323/88857185-b4dc1d00-d1ed-11ea-8182-6bb523ccc47f.PNG)

**Comment by banesullivan** [comment]
Please include the code you used to create this figure and the mesh you are working with. Otherwise, there's really not much we can do to help.

--------

> Is there any way of making the elevation filter more saturated?

The filter has nothing to do with how the mesh is displayed when plotting. For this, you need to pass different arguments to the `add_mesh` or `plot` methods. Please share your current code, and I can point you to where you can control these things.

> Is there any way of achieving more distinction between the colours? So for example i'd see the difference between red and yellow more clearly. (I changed the pv theme to rainbow in the source code to achieve the rainbow colouring).

Rainbow is a terrible choice of colormap if you are looking for a distinction between colors (it is not perceptually linear) - try a colormap like Viridis or any of the awesome ones from [`colorcet`](https://colorcet.holoviz.org) (which we support if `colorcet` is installed). See [this](https://wiki.seg.org/wiki/How_to_evaluate_and_compare_color_maps) for more details on perceptually linear colormaps (or any of [MyCarta's blogs](https://mycarta.wordpress.com/tag/perceptual-colormaps/))

Next, you should be changing the source to adjust the colormap. Simply pass the `cmap` argument when plotting. If you haven't, you should peruse the [examples gallery](https://docs.pyvista.org/examples/index.html#plotting) to become more familiar with PyVsita plotting.

Further, I suspect you are plotting a `Plane` that doesn't have many nodes/data points and thus the colors have to be interpolated between those points because your mesh is so sparse (hence the smoothness). Try using an actual mesh like the one in the lower figure you show.

> I understand the box creates the perfect gradient but even on more scattered data it is still looking very unsaturated.

Please provide some example data and the code you have to produce the issue and I will help you work to achieve a better result.

**Comment by banesullivan** [comment]
If you use an actual mesh and not simple geometry, you will see something more like what you ahve in the second figure:

```py
import pyvista as pv
from pyvista import examples

mesh = examples.download_st_helens().warp_by_scalar()

p = pv.Plotter()
p.add_mesh(mesh, cmap='rainbow')
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/88873552-e0113d00-d1ea-11ea-96ad-3e4fe460a119.png)

or you could reduce the number of colors:

```py
p = pv.Plotter()
p.add_mesh(mesh, cmap='rainbow', n_colors=12)
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/88873572-eef7ef80-d1ea-11ea-9abc-628841490ac8.png)

**Comment by montymagic9** [comment]
Thank you for your response. Using color map 'jet' worked to my needs.
