### ISSUE TITLE
Slider widget overlaying new meshes each time the value is changed

### ISSUE THREAD

**Issue by ellenorfoster** [pyvista/pyvista-support#224]
## Description
We are trying to use the slider widget on a mesh in order to change the number of iterations done when smoothing the mesh. Instead of changing the smoothness of the one original mesh, it is instead overlaying a new mesh each time the slider is moved. Since the smoother meshes are smaller in area, we are unable to see any of the smoother meshes once you move the slider to the least smooth end. Below is the current code we are using with an example cow mesh:

``` 
def smooth_mesh(iteration):
    mesh = pv.read("cow.ply")
    itr = int(iteration)
    surf = mesh.extract_geometry()
    mesh2 = surf.smooth(n_iter= itr)
    p.add_mesh(mesh2)
    return 
```
``` 
p = pv.Plotter(notebook = False)
p.add_slider_widget(smooth_mesh, [0 , 1000] )
```
Any help to resolve this issue would be greatly appreciated.

**Comment by banesullivan** [comment]
It is doing this because you repeatedly call `p.add_mesh` with a new mesh (the new mesh is generated by the `smooth` filter). The documentation for the widgets were recently rewritten to clarify this issue and are available at `dev.pyvista.org` [here](https://dev.pyvista.org/plotting/widgets.html#widgets). In those examples a tip was added:

> Note that we have to pass a name when calling add_mesh to ensure that there is only one set of glyphs plotted at a time.

In brief, use the `name` argument for `add_mesh` to update the mesh rather than continually add it. E.g.

```py
def smooth_mesh(iteration):
    mesh = pv.read("cow.ply")
    itr = int(iteration)
    surf = mesh.extract_geometry()
    mesh2 = surf.smooth(n_iter= itr)
    p.add_mesh(mesh2, name="smoothed")
    return 
```

**Comment by banesullivan** [comment]
Every mesh in the plotter's scene has a unique name. By specifying `name` in `add_mesh` you tell the plotter to find an existing mesh with that name and replace it
