### ISSUE TITLE
Calculation of geodesic on loaded surface mesh

### ISSUE THREAD

**Issue by julianpw** [pyvista/pyvista-support#233]
I've generated a surface with another software (saved as .obj), the representation of which looks fine in pyvista;

```
import pyvista as pv
surface = pv.read('myscene.obj')
plotter = pv.Plotter()

plotter.add_mesh(surface, show_edges=True, color='white', opacity=1)
plotter.add_mesh(pv.PolyData(surface.points), color='red',
                             point_size=4, render_points_as_spheres=True )

```
![mesh](https://user-images.githubusercontent.com/69905613/90637735-a8674500-e22c-11ea-96df-08c6dc312e31.png)

Now, I would like to calculate the geodesic path and distance for arbitrary points on the surface. Following the example in the documentation, it should be straightforward, but something seems off with the mesh, as it throws an error.

```
v1, v2 = (50, 1000)
g = surface.geodesic(v1, v2)
gd = surface.geodesic_distance(v1, v2)

  File "pyvista/core/filters.py", line 3181, in geodesic
    output["vtkOriginalPointIds"] = original_ids

  File "pyvista/core/common.py", line 909, in __setitem__
    raise_not_matching(scalars, self)

  File "pyvista/utilities/helpers.py", line 553, in raise_not_matching
    '({}). '.format(mesh.n_cells) )

ValueError: Number of scalars (1) must match either the number of points (0) or the number of cells (0). 
```

I am not quite sure how to interpret this error, as `print(surface)` reports 39676 cells and 119028 points, and 2 arrays 'GroupIds' and 'Normals'.

Is there a way to calculate a geodesic on this surface? I'd be very grateful for any suggestion!

**Comment by banesullivan** [comment]
Can you share this mesh?

**Comment by julianpw** [comment]
Here is a download link: https://drive.switch.ch/index.php/s/4fdZVFtsDTBJHuk

**Comment by banesullivan** [comment]
Okay, the problem is there the mesh's cell connectivity is massively disconnected. The two vertices you are interested in are in diferent conencted regions of the mesh (use the `connectivity` filter to realize this):

```py
>>> conn = surface.connectivity()
>>> print(conn.point_arrays['RegionId'][v1], conn.point_arrays['RegionId'][v2] )
16 333
```




You will need to run a `clean()` filter fix mesh connectivity by merging duplicate points then use the `split_bodies` filter to seperate all the truly disconnected parts of your mesh:

```py
clean = surface.clean()
bodies = clean.split_bodies(label=True)
bodies.plot(multi_colors=True, opacity=0.25)
```

<img width="624" alt="Screen Shot 2020-08-19 at 10 04 51 AM" src="https://user-images.githubusercontent.com/22067021/90660719-83121100-e203-11ea-8f03-8fb2a08dde78.png">


Then figure out which body the region of interest is, and the new point IDs of your vertices of interest and then run the geodesic filter.

Though we should fix this bug in the geodesic filter to raise an error of no path is found like this

**Comment by julianpw** [comment]
Fantastic! I'm very glad for the quick help, would have taken me ages to figure this out. The last block was the one of interest, so I proceeded like this:

```
name = bodies.keys()[-1]
points = bodies[name]
surf = points.extract_surface()

geod_path = protein_surface.geodesic(v1, v2)
geod_distance = protein_surface.geodesic_distance(v1, v2)
```
Just what I needed!
