### ISSUE TITLE
Creating add_checkbox_button on the fly.

### ISSUE THREAD

**Issue by Davegis16** [pyvista/pyvista-support#269]
Hi,
Is it possible in pyvista to create several add_checkbox_buttons on the fly, I looked at writting a loop to create the buttons, but I could not see a way of implementing callbacks (SetVisibility) for each button once they are created on the fly. See code below.
Thanks,
Dave

```
Geologynames = ["QTC","QTW","PHS","PHV","PHW","PHC","IPF","IPC","IRF","HEF","HGF","TRN","CAP","LAT"]
Geologycolours = ["ff0000","28e5da","0000ff","ffff00","c8bebe","f79292","ffffff","f18c1d","23dcaa","d785ec","9d5b13","e4e0b1","894509","af45f5"]

def toggle_vis_Geology(flag):
    Geology1.SetVisibility(flag)

Threshcount = 1
Colourcount = 0 
Startpos = 12
for names in Geologynames:   
    p.add_checkbox_button_widget(toggle_vis_Geology, value=True,position=(5.0, Startpos), size=30, border_size=1, color_on=Geologycolours[Colourcount], color_off='grey', background_color='grey')
    Startpos = Startpos + 30 
    Colourcount = Colourcount + 1
```

**Comment by banesullivan** [comment]
So the problem is comming from the callback not referencing the correct object. This is a general programming issue where if you have a reference to an object outside the scope of the calling function, that object is subject to change and you can't maintain state across your functions. For instance, this is equivalent to doing:

```py
callbacks = []
for i in range(3):
    callbacks.append(lambda: print(i))
callbacks[0]()
callbacks[1]()
callbacks[2]()
```

The intuitive assumption would be that this outputs `0 1 2` but it actually outputs `2 2 2` because the state of `i` is not preserved when the function is created but it is a single instance set as 2 outside the scope of the function when those functions are called. To deal with this, you can capture the state of that object through a class:

```py
class MyCallback:
    def __init__(self, ref):
        self.ref = ref
    
    def __call__(self):
        print(self.ref)

callbacks = []
for i in range(3):
    callbacks.append(MyCallback(i))
callbacks[0]()
callbacks[1]()
callbacks[2]()
```

which will output `0 1 2`.

-------

Now we have to do the equivalent with the `add_checkbox_button_widget` method on the plotter. Here is a simple example using your list of colors that you can adopt:

```py
import pyvista as pv

colors = ["ff0000","28e5da","0000ff",
          "ffff00","c8bebe","f79292",
          "ffffff","f18c1d","23dcaa",
          "d785ec","9d5b13","e4e0b1",
          "894509","af45f5"]


class SetVisibilityCallback:
    def __init__(self, actor):
        self.actor = actor
    
    def __call__(self, state):
        self.actor.SetVisibility(state)


p = pv.Plotter(notebook=False)

Startpos = 12
for i, color in enumerate(colors): 
    a = p.add_mesh(pv.Sphere(center=(0,0,i)), color=color)
    # Make a seperate callback for each widget
    callback = SetVisibilityCallback(a)
    p.add_checkbox_button_widget(callback, value=True, 
                                 position=(5.0, Startpos), size=30, 
                                 border_size=1, 
                                 color_on=color, 
                                 color_off='grey', 
                                 background_color='grey')
    Startpos = Startpos + 30 

p.show()
```

![2020-11-03 20 47 34](https://user-images.githubusercontent.com/22067021/98067062-f47e5a80-1e15-11eb-94dc-0904d0227963.gif)

**Comment by Davegis16** [comment]
That is brilliant, I am still learning python, so that is very useful and you explained it clearly how to get the actor and the state of the buttons. It may be useful to put on the examples page. I will go away and change my code. Thanks

**Comment by akaszynski** [comment]
Opening this as we need this as an example

**Comment by banesullivan** [comment]
Ah. Yeah. We can finally have widgets in the examples in the gallery after https://github.com/pyvista/pyvista/pull/983 since it then adds the interactor during offscreen plotting

**Comment by akaszynski** [comment]
> Ah. Yeah. We can finally have widgets in the examples in the gallery after [pyvista/pyvista#983](https://github.com/pyvista/pyvista/pull/983) since it then adds the interactor during offscreen plotting

Exactly.  I'll work on that today as I need it soon.

**Comment by banesullivan** [comment]
I can do a follow up PR moving all the widgets examples into the gallery
