### ISSUE TITLE
Creating surface mesh from point cloud

### ISSUE THREAD

**Issue by JasonTLin** [pyvista/pyvista-support#30]
## Description

I am trying to take my point cloud data and convert to a surface mesh. My current approach is using a delaunay 3d filter but that creates sharp edges in the data which won't smooth well. 
[block.xlsx](https://github.com/pyvista/pyvista-support/files/3436567/block.xlsx)

```python
    import pandas
    import pyvista
    import pymeshfix

    coordinates = pandas.read_csv("block.csv")
    coordinates = vtk_blocks[['Points:0','Points:1','Points:2']].values
    vtk_blocks = pyvista.PolyData(coordinates)
    shell = vtk_blocks.delaunay_3d(alpha=17).extract_geometry().clean()
    shell = shell.extract_geometry().tri_filter()
    shell = shell.split_bodies()
    decimated_shell = pv.MultiBlock()
    for block in shell:
        block = pymeshfix.MeshFix(block.extract_geometry())
        block.repair()
        block = block.mesh
        block = block.extract_geometry().smooth(n_iter=180)
        decimated_shell.append(block)
```

**Comment by banesullivan** [comment]
Hi @JasonTLin - thanks for posting here!

Attached is a script to use a Delaunay 3D filter to make surface meshes of your point cloud.

```py
import pandas as pd
import numpy as np
import pyvista as pv
import pymeshfix as mf

f = 'testdata_block_model.csv'
df = pd.read_csv(f)

pc = pv.PolyData(df[['Points:0', 'Points:1', 'Points:2']].values)
pc['MDIST'] = df['MDIST'].values
pc['gain'] = df['gain'].values

pc.plot(show_grid=True)
```
![download](https://user-images.githubusercontent.com/22067021/61966590-33293200-af90-11e9-94d7-8cbddb1cc7f2.png)

```py
alpha = 17.

volume = pc.delaunay_3d(alpha=alpha)

# Extract some grade of the volume
ore = volume.threshold(30)

p = pv.Plotter(shape=(1,3), notebook=False)

p.subplot(0,0)
p.add_mesh(pc)
p.show_grid()

p.subplot(0,1)
p.add_mesh(volume)
p.show_grid()

p.subplot(0,2)
p.add_mesh(ore, opacity=0.75)
p.add_mesh(volume.slice('x', [23200, 9191.25, 9795.0]))
p.add_mesh(volume.slice('z', [22875, 9200, 10e3]))
p.show_grid()

p.link_views()
p.show()
```

<img width="1962" alt="Screen Shot 2019-07-26 at 10 16 42 AM" src="https://user-images.githubusercontent.com/22067021/61966603-40deb780-af90-11e9-9e5e-f8492cb9737a.png">

Rather than using the split bodies filter, lets split the bodies using a cutting plane. This is because the meshes are of poor quality at this point and need to be repaired. The parts that need repair are tricking the `split_bodies` filter and it won't work properly:

```py
shell = volume.extract_geometry().clean()
center = pc.center
center[1] = 9200
shell_a = volume.clip('y', center)
shell_b = volume.clip('-y', center)
shells = pv.MultiBlock([shell_a, shell_b])

# Now fix and smppth
decimated_shells = pv.MultiBlock()
tetrad = pv.MultiBlock()
for block in shells:
    block = mf.MeshFix(block.extract_geometry().tri_filter())
    block.repair()
    block = block.mesh
    block = block.smooth(n_iter=180)
    decimated_shells.append(block)
```

<img width="1124" alt="Screen Shot 2019-07-26 at 10 31 38 AM" src="https://user-images.githubusercontent.com/22067021/61966721-91eeab80-af90-11e9-88e9-707975d3b320.png">

**Comment by JasonTLin** [comment]
Thanks for all the help. I was having a lot of trouble properly smoothing out the dataset.

**Comment by banesullivan** [comment]
Happy to help!

I think it all came down to the `split_bodies` filter not being able to handle the delaunayed mesh since it had holes/seperations all over
