### ISSUE TITLE
boolean_union returns empty

### ISSUE THREAD

**Issue by houhou993** [pyvista/pyvista-support#305]
[2components.zip](https://github.com/pyvista/pyvista-support/files/5585670/2components.zip)

Attached 2 files are the 2 .stl files I used in my case
My code is as following:
```py
import pyvista 

component1 = pyvista.read("component1.stl")
component2 = pyvista.read("component2.stl")
unionstl = wrapped2.boolean_union(wrapped3)
unionstl.plot(show_edges=True, show_bounds = True, show_axes = True)

wrapped1 = pyvista.wrap(component1) 
wrapped2 = pyvista.wrap(component2) 
unionstl = wrapped2.boolean_union(wrapped3)
unionstl.plot(show_edges=True, show_bounds = True, show_axes = True)
```
And both plot gives error "ValueError: Empty meshes cannot be plotted. Input mesh has zero points." However, both PyVista.read and PyVista.wrap are working fine. (You can try to plot component1/component2/wrapped1/wrapped2, they all plot the correct geometry)

**Comment by houhou993** [comment]
Also I forgot to add, the type for both components are "pyvista.core.pointset.PolyData", so the requirement of input type for boolean_union should be satisfied

**Comment by akaszynski** [comment]
The issue is that these meshes do not have common volume and it seems that the union filter implemented within VTK doesn't actually perform a [union](https://en.wikipedia.org/wiki/Union_(set_theory)) property...

<img src="https://user-images.githubusercontent.com/11981631/100057245-4f3b1e80-2de4-11eb-85b7-7ef76bea7a70.png " width="400" height="400">

You can get around this by simply adding the two meshes together to perform the union with:
```py
unionstl = component1 + component2
```

**Comment by houhou993** [comment]
I see. The meshes indeed do not have a common volume, however, they do have a common surface between them. If I use add, that surface would still be there and thus gaining a geometry with a surface inside it. Is it correct to say this case can't be handled with vtk's union function?

**Comment by akaszynski** [comment]
> Is it correct to say this case can't be handled with vtk's union function?

It would appear so.

**Comment by houhou993** [comment]
Thank you! I will close this issue then.
