### ISSUE TITLE
Split quads mesh to triangular mesh. Retopology

### ISSUE THREAD

**Issue by megahard25** [pyvista/pyvista-support#332]
I have a 3D Model of human head. (It is [ICT Face Model Light](https://github.com/ICT-VGL/ICT-FaceKit))
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/47577353/103542888-b56c9400-4eae-11eb-9726-5a7fc91bc1bb.png">
As shown, it has quadratic mesh and mesh.faces shape is (131372,). The number 131372 is divisible by 4, which corresponds to a quad topology.

I want to convert quad mesh to triangular mesh.
I tried to use mesh.triangulate() method and the result is shown below:
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/47577353/103543764-1779c900-4eb0-11eb-8641-844e2b670347.png">
It seems that the conversion was successful, but if you look at the shape of mesh.faces, you will see that it is equal to (208880,), where the number 208880 is not divisible by 3, but is divisible by 4. 

I need the mesh.faces shape to be divisible by 3 after triangulation.
As far as I understand, this result means that the topology of the model has not changed and we need do retopology procedure.

Please give me advice on how I can achieve the desired result.
Thank you!

**Comment by akaszynski** [comment]
That's because `mesh.faces` will include a "header" for each face that indicates the number of points in that face.  For example, the faces with points `[0, 1, 2]` and `[10, 11, 12]` will resolve within VTK as:

```
[3, 0, 1, 2, 3, 10, 11, 12]
```

The `3` indicates the number of points in the face and followed by the indices in the faces.

To be 100% sure, you can verify the mesh is composed only of triangles with the following.  Note that the size of "faces" is still divisible by 4:

```py
>>> import pyvista as pv
>>> mesh = pv.Sphere()
>>> mesh.is_all_triangles()
True

>>> mesh.faces[:12]
array([ 3,  2, 30,  0,  3, 30, 58,  0,  3, 58, 86,  0])

>>> mesh.faces.size % 4
0

>>> mesh.plot(show_edges=True)
```

![image](https://user-images.githubusercontent.com/11981631/103589845-9ae3ec00-4ea9-11eb-80b0-93e4c93007e1.png)

**Comment by megahard25** [comment]
Thank you!
