### ISSUE TITLE
Mesh data input for Graph

### ISSUE THREAD

**Issue by roaasoloh** [pyvista/pyvista-support#339]
## Description
Kindly what I'm trying to do is to process the mesh file I have using Pyvista for making it a Graph.
The graph is a set of vertices and edges, using pyvista I was able to get the vertices, and faces, and using `extract_all_edges` I'm getting a `list of array`, that I'm not getting so much how to process with :(
In another way, I'm trying to model my mesh as a graph.

## Example Data
So assuming I have the following:
```
mesh = pv.read("13.off")
coord = mesh.points
poly = mesh.extract_surface()
faces = np.asarray(poly.faces).reshape((-1, 4))[:, 1:]
 ```
So the output of `faces` is: 
```
[[   0    1    2]
 [   0    3    1]
 [   0    4    3]
 ...
 [ 194 8537  176]
 [ 194 8642 8537]
 [8607 8642  194]]
```
That means that if I understand correctly: `face 1` connects `n_0` n_1` n_2` etc...
My idea how I may get that there's an edge between `n_0` and `n_1`  without redundancy since it's obviously shown in `face 2 ` that nodes `n_0` and `n_1` are connected as well.
 
At the same time if I try
```
poly.extract_all_edges().lines
```
I will get this output
```
[   2    0    1 ...    2  194 8642]
``` 
which I didn't get the idea behind.

Thanks for your time and support.

**Comment by akaszynski** [comment]
Basically, the way VTK connectivity arrays work is that they first tell the number of items in a line/face/cell, and then to proceed to list the indices of those items.  For example, in `poly.extract_all_edges().lines`, there are two items in the first line segment, composed of points with the indices 0 and 1.  The last line segment also contains two points, composed of indices 194 and 8642.

The reason why ``np.asarray(poly.faces).reshape((-1, 4))[:, 1:]`` works, is because we're reshaping the face connectivity array and ignoring the first column.  You could do the same thing with the lines array with:

```
my_line_arr = np.asarray(poly.lines).reshape((-1, 3))[:, 1:]
```

Note how we're using 3 instead of 4 to reshape the array, since each line segment contains three items (the first being the number of items in that line segment).

**Comment by roaasoloh** [comment]
Thank you Sir for your fast response.
It's so much appreciated.
I did like what mentioned and got this: 
```
[[   0    1]
 [   1    2]
 [   2    0]
 ...
 [ 176 8537]
 [ 194 8537]
 [ 194 8642]]
```
So this means for me each two connected vertices, correct?
And by doing: 
```
initiate_vertex = my_line_arr[:,0]
target_vertex = my_line_arr[:,1]
```
This will give the edge between vertices from  `vertex[i]` to `vertex[j]`
Correct like that?

Just to ensure I'm on the correct road.

And just one more thing please, if I need to get the 3d coordinates of an index, this will be done through?

Thank you again.

**Comment by akaszynski** [comment]
> This will give the edge between vertices from vertex[i] to vertex[j]
Correct like that?

Correct.

> And just one more thing please, if I need to get the 3d coordinates of an index, this will be done through?

Assuming your `PolyData` object is `poly`, then the coordinates are then `poly.points`, which you can index just like a numpy array (since it is a numpy array).  So, `poly.points[0]` are the coordinates of the first point.
