### ISSUE TITLE
Adding or updating the default axis labels.

### ISSUE THREAD

**Issue by leonfoks** [pyvista/pyvista-support#348]
Hello!

I'm finally getting PyVista incorporated into GeoBIPy, and I have a simple question.  How do I update the axis labels? I can't seem to find an example in the docs.

Heres your uniform grid example but with show_grid added.
```
import pyvista as pv
values = np.linspace(0, 10, 1000).reshape((20, 5, 10))
values.shape

# Create the spatial reference
grid = pv.UniformGrid()

# Set the grid dimensions: shape + 1 because we want to inject our values on
#   the CELL data
grid.dimensions = np.array(values.shape) + 1

# Edit the spatial reference
grid.origin = (100, 33, 55.6)  # The bottom left corner of the data set
grid.spacing = (1, 5, 2)  # These are the cell sizes along each axis

# Add the data values to the cell data
grid.cell_arrays["values"] = values.flatten(order="F")  # Flatten the array!

# Now plot the grid!
grid.plot(show_edges=True, show_grid=True)
```

How do I change the label "z_axis" etc.? 

This would be useful for a named array like what xarray have, and my statistical array in geobipy.

Also, I noticed you added the example of the flight line following 2.5D cross-section!  Thanks for that!!

**Comment by banesullivan** [comment]
Hey Leon!! Apologies for the slow response!

This is not well documented (if documented at all), but you can change the labels on the grid and axes quite easily. In essance you need to directly use the `Plotter` rather than the `.plot` convenience method as you'll need to call a few specific methods with custom options.

Here is a basic example:

```py
import pyvista as pv
from pyvista import examples
mesh = examples.download_st_helens().warp_by_scalar()

labels = dict(zlabel='Z!!!!', xlabel='Bane Rules', ylabel='wassssup')

p = pv.Plotter()
p.add_mesh(mesh)
p.show_grid(**labels)
p.add_axes(**labels)
p.show()
```

- For the grid: You can find these options documented in the [`show_bounds`](https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.show_bounds) method which [`show_grid`](https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.show_grid) wraps.
- For the axes: You can find this documented in [`add_axes`](https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.add_axes)

**Comment by leonfoks** [comment]
Great! Thanks Bane! I think those axis names might be perfect for the St Helen's topo :P

**Comment by Khalilsqu** [comment]
`TypeError: show_axes() got an unexpected keyword argument 'zlabel'`

**Comment by Khalilsqu** [comment]
Thanks for this awesome library. 

How can I get rid of scientific notation tick labeling? and also increase the padding between axis labels and axis lines?

![image](https://user-images.githubusercontent.com/22060413/188456403-055ff017-a847-48aa-aab2-47b17fa005eb.png)

**Comment by Khalilsqu** [comment]
Thanks for this awesome library,

how can I prevent scientific notation ticklabels in both axes and the colorbar?

I tried `fmt="%.0f"` but it did not work.

![image](https://user-images.githubusercontent.com/22060413/188462103-511aca94-ad5c-4cde-ba3b-f188ab04f202.png)
