### ISSUE TITLE
Volume (PLY) contains a 3D-point

### ISSUE THREAD

**Issue by hugosciascia** [pyvista/pyvista-support#349]
Hello everyone, thanks for this helpfull Python extension !

Thanks to PyVista, I defined a volume (ply) from a cloud point :
`cloud = pv.PolyData(my_data.T)`
`volume = cloud.delaunay_3d(alpha=0.25)`
`shell = volume.extract_geometry()`

I would like to know now if there is a way to test if the volume (.PLY file) contains a 3D-point.
Like volume.contains(point) return true or false.

Thanks in advance !

**Comment by akaszynski** [comment]
By "contains" do you mean that the point is geographically inside (enclosed) by the mesh?  Or do you mean if there is a point that is similar to a point?

If it's the latter, you can try:
```py
dist = shell.points - point
```
Then check if there's a distance that's within a minimum threshold (because your point might not be exactly "in" the points array.

**Comment by hugosciascia** [comment]
Yes I mean enclosed in the mesh, but my mesh is computed by a point cloud which are all to an equal distance between them (like a discretized mesh).

So you solution should works, I keep you informed !

**Comment by hugosciascia** [comment]
Ok it's working great, in fact I did not need PyVista for that just my CSV

Thanks a lot !
