### ISSUE TITLE
Grid planar view & parallel projection

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#38]
I am trying to view my 3d plot in the xy plane as a slice of the 3d model lat a given elevation.
I have been able to add a grid top the plot although it shows a box. How would I go about having the grid only be shown in the 2d plane (not as a box) at the elevation of the clip? Also, can I view the 2D plane as a parallel projection? I know this can be done in paraview so I assume it can also be done in pyvista.

code:
```
p = pv.Plotter(notebook=False)
p.add_mesh(bpoly, cmap='coolwarm_r',scalars='shortest distance',render_points_as_spheres=True)
for i in range(0, len(DH)):
    p.add_mesh(globals()['seg{}'.format(i)],color='yellow')
p.add_mesh(polyLine,color='magenta')
p.view_xy(negative=False)
p.show_axes()
p.show_grid()
p.plot(screenshot='plot.png')
```

**Comment by banesullivan** [comment]
@laserman781 - since you posted this twice, once in the main PyVista repo and once here, I'm going to split the two parts of this issue into 1. a question which I'll answer here, and 2. a feature request which I will address in https://github.com/pyvista/pyvista/issues/337

> How would I go about having the grid only be shown in the 2d plane (not as a box) at the elevation of the clip?

Simply pass in the bounds of the box you'd like to use - if you want a 2D box, then make the min/max for the plane of no variation the same. For example, in the snippet below, I add a 2D axes grid at the bottom of Mt. St. Helens. All you need to do is specify the bounds argument for `show_grid` which is a length six array of min/max for each axes (e.g. `[xmin,xmax, ymin,ymax, zmin,zmax]`).

```py
import pyvista as pv
from pyvista import examples

mesh = examples.download_st_helens().warp_by_scalar()

bounds = mesh.bounds
bounds[5] = bounds[4]

p = pv.Plotter()
p.add_mesh(mesh)
p.show_grid(bounds=bounds)
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/62249475-c060f200-b3a7-11e9-97dc-ef5104a12576.png)

**Comment by banesullivan** [comment]
FYI: `show_grid` is an alias/helper for `show_bounds` - so you might not have seen all the options available unless looking at the docs for `show_bounds`: https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.show_bounds
