### ISSUE TITLE
How to create two or more seperate windows when plotting?

### ISSUE THREAD

**Issue by wanggy-1** [pyvista/pyvista-support#452]
The subplot window is too crowded. How to create two or more seperate windows when plotting?

**Comment by akaszynski** [comment]
> The subplot window is too crowded. How to create two or more seperate windows when plotting?

Use `pyvistaqt`'s `BackgroundPlotter.  See docs here: https://qtdocs.pyvista.org/

**Comment by Johndeep** [comment]
Even if this issue is closed, since wanggy-1 is satisfied with using pyvistaqt, I am not.

Aren't there alternative ways to create two or more separated pyvista windows **without the use of pyvistaqt, qt or any external (third party) library**? Aren't there ways with only Python tools and libraries?
Isn't it possible to tell pyvista vanilla to just not block everything (by it being called in a separated thread internally or something)?

I've tried to actually use `threading` within Python, but every time, the second pyvista plot complains about "AttributeError: module 'pyvista' has no attribute 'Plotter'", which makes no sense, since the first window pops up just fine.

I also tried with `concurrent.futures`, but this time, either the second window pops up only after closing the first one, or not at all. If I exit the first window with "r" or "q", the second window will not pop up at all.

I might add that I'm on Ubuntu 24.04 with Wayland. But I assume that the situation won't differ regarding the OS or Display manager.

**Comment by Johndeep** [comment]
As of this writing, I finally found a pure Python solution for this question.

I want to share this here, since it fits the question, despite the issue being closed. I just don't want to duplicate this and furthermore, search engines and AI engines might find this anyway.

So, besides `threading` and `concurrent.future`, which both based on threads, you need to use processes, like `multiprocessing`. Because the context will not be shared, stupid import/library/context errors won't occur.

A very simple example:

```Python
from multiprocessing import Process
import pyvista as pv

def task(title: str = "Nah"):
    mesh = pv.Sphere()
    mesh.plot(show_edges=True, text=title)

process_list = []
for name in ["Task 1", "Task 2", "Task many", None]:
    process_list.append(Process(target=self.task, args=(name,)))
    process_list[-1].start()

for elem in process_list:
    elem.join()
    
print("The End")
```
Easy, pure Python and no need for any extra library. **For this case at least.** Btw. the plots can even have the same name, since nothing is shared anyway. The plots are not blocking each other in any instances, almost like you would run the app several times but with different parameters.
