### ISSUE TITLE
Calculating volume of clipped 3D mesh

### ISSUE THREAD

**Issue by GreKro** [pyvista/pyvista-support#71]
Hello everyone,

I would like to calculate volume of 3D mesh of iregular shape similar to water container. In my case I would like to create some tresholds on Z axis, for example I want to calaculate volume  for first 10 centimeters of height (Z axis) from bottom of contairner, next 20, 30 etc. 

At first I started with simply cylinder with known dimensions, radius of 1 meter and height of 5 meters and I would like to calculate volume for first meter of this cylinder. 
To do it I use .volume function and .clip to manipulate mesh height.
The volume of whole cylinder (r=1, h=5) is similar to mathematical cylinder volume (V= Pi * r^2 * h)

pyvista vol = 15.69
mathematical vol = 15,70

and its OK, but when I clip first meter of this cylinder (r=1, h=1) differences is quite high
pyvista vol = 4.68
mathematical vol = 3,14

Anyone can help me with understand why this approach dont work ? or can explain how to do it properly ?

Best regards,
GreKro

code below:

```py
import pyvista as pv
cyl = pv.Cylinder(direction=(0.0, 0.0, 1.0), radius=1.0, height=5.0)
cyl_clipped = cyl.clip('z', value=1.0, origin=(0.0, 0.0, -2.5))

cyl.volume
cyl_clipped.volume

p = pv.Plotter()
p.add_mesh(cyl, style='wireframe', color='blue', label='Input')
p.add_mesh(cyl_clipped, label='Clipped')
p.add_legend()

p.show()
```
![obraz](https://user-images.githubusercontent.com/26602062/67617164-a7b67b80-f7e0-11e9-9ea4-dac9499ecd31.png)

**Comment by banesullivan** [comment]
The volume calculation of the clipped mesh is incorrect because it is not a closed surface while the input cylinder is a completely closed surface. This is why you can easily compute the volume of the starting cylinder and not the clipped cylinder.

In order to compute a volume, the volume must be fully defined/enclosed so you'll have to repair the surface of your mesh first. Fortunately, @akaszynski has built a wrapper around the MeshFix software that plays nicely with PyVista for doing just that! Check it out here: http://pymeshfix.pyvista.org

Installation should simply be:

```
pip install pymeshfix
```

-----

Here is some code to perform your task and properly compute the volume:

```py
import pyvista as pv
import pymeshfix

cyl = pv.Cylinder(direction=(0.0, 0.0, 1.0), radius=1.0, height=5.0)
cyl_clipped = cyl.clip('z', value=1.0, 
                       origin=(0.0, 0.0, -2.5))

# Be sure to triangulate!!!
fixer = pymeshfix.MeshFix(cyl_clipped.triangulate())
fixer.repair()
repaired = fixer.mesh
print("Clipped volume: {:.3f}".format(repaired.volume))
``` 
Clipped volume: 3.140

```py
p = pv.Plotter(shape=(1,2))
p.add_mesh(cyl_clipped, show_edges=True)
p.add_text("Not a closed volume: {:.3f}".format(cyl_clipped.volume))
p.show_grid()
p.subplot(0,1)
p.add_mesh(repaired, show_edges=True,)
p.show_grid()
p.add_text("A closed volume: {:.3f}".format(repaired.volume))
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/67625069-692bbb80-f7f6-11e9-98b0-881ce8954cf9.png)




```py
p = pv.Plotter()
p.add_mesh(cyl, style='wireframe', color='blue', label='Input')
p.add_mesh(repaired, label='Clipped')
p.add_legend()
p.show_grid()
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/67625026-d8ed7680-f7f5-11e9-9366-4eda3c2400d0.png)

**Comment by akaszynski** [comment]
@banesullivan thanks for answering this!

**Comment by GreKro** [comment]
@banesullivan thanks a lot for comprehensive answer
