### ISSUE TITLE
pyvista vs pvgeo

### ISSUE THREAD

**Issue by bistek** [pyvista/pyvista-support#98]
Hello, what are the differences between PyVista and PVGeo?

On the PVGeo documentation read that PVGeo can be used inside and outside Paraview, and the link on how to use PVGeo in Paraview is broken, so it is difficult to understand.

I have the impression that either (1) PyVista is a library on which PVGeo is built (so maybe PVGeo has more tools or is easier?), or that (2) PVGeo is an older project and PyVista is more regularly updated (so we should use PyVista and not PVGeo?).

Thanks very much!

**Comment by bistek** [comment]
Ooops... I've found the instructions for installation here.

http://pvgeo.org/overview/getting-started.html

So it looks like that PVGeo is (1) written in Python 2.7 (wile PyVista is 3.x) and it is strictly related to Paraview.

It remains one open point: which one allows more "things to be done"?

Thanks!

**Comment by banesullivan** [comment]
In brief, PVGeo is an extension package to either ParaView *or* PyVista. You can think of PyVista as a Python equivalent of ParaView as ParaView is a GUI wrapping of VTK and PyVista is a Python wrapping of VTK - they are both exposing much of the same functionality and those both are general 3D visualization tools on their own.

PVGeo comes in as a set of a few file readers and filters that make sense for geo-datasets. so if you're looking at PVGeo and PyVista and wondering...

> which one allows more "things to be done"?

PyVista wins by a long shot. PVGeo is just a set of a few file readers and filters that plug into PyVista and/or ParaView

> So it looks like that PVGeo is (1) written in Python 2.7 (wile PyVista is 3.x) and it is strictly related to Paraview.

Not necessarily. Since ParaView leverages Python 2.7 (this is rapidly changing though), a lot of effort has been put into making sure PVGeo is both Python 2.7 and 3.x compliant. While PVGeo was originally built to only be used in ParaView, these days I recommend folks to pair it with PyVista in a standard Python environment outside of ParaView. For example, checkout PVGeo's [example gallery](https://pvgeo.org/examples/index.html) where we demo how to use it with PyVista.

**Comment by bistek** [comment]
Thanks very clear now!
